// Generated by tools/registry. Do not edit by hand.
// Add or remove a numbered content/exercises/*.typ file, then run `just registry`.
#import "exercises/0001.typ": item as ex0001
#import "exercises/0002.typ": item as ex0002
#import "exercises/0003.typ": item as ex0003
#import "exercises/0004.typ": item as ex0004
#import "exercises/0005.typ": item as ex0005
#import "exercises/0006.typ": item as ex0006
#import "exercises/0007.typ": item as ex0007
#import "exercises/0008.typ": item as ex0008
#import "exercises/0009.typ": item as ex0009
#import "exercises/0010.typ": item as ex0010
#import "exercises/0011.typ": item as ex0011
#import "exercises/0012.typ": item as ex0012
#import "exercises/0013.typ": item as ex0013
#let exercises = (ex0001, ex0002, ex0003, ex0004, ex0005, ex0006, ex0007, ex0008, ex0009, ex0010, ex0011, ex0012,ex0013)

#let exercise-at(serial) = {
  let matches = exercises.filter(item => item.serial == serial)
  assert(matches.len() == 1, message: "unknown or duplicate exercise serial " + str(serial))
  matches.first()
}
