// Generated by scripts/generate_registry.py. Do not edit by hand.
// Add or remove a numbered content/exercises/*.typ file, then run `just registry`.
#import "exercises/0001.typ": item as ex0001
#import "exercises/0002.typ": item as ex0002
#import "exercises/0003.typ": item as ex0003
#import "exercises/0004.typ": item as ex0004
#import "exercises/0005.typ": item as ex0005
#import "exercises/0006.typ": item as ex0006

#let exercises = (ex0001, ex0002, ex0003, ex0004, ex0005, ex0006,)

#let exercise-at(serial) = {
  let matches = exercises.filter(item => item.serial == serial)
  assert(matches.len() == 1, message: "unknown or duplicate exercise serial " + str(serial))
  matches.first()
}
