#!/usr/bin/env python3
"""Generate the static Typst exercise registry from numbered source files."""

from __future__ import annotations

import argparse
from pathlib import Path

from common import CONTENT, CheckError, fail, rel

REGISTRY = CONTENT / "exercise-registry.typ"


def exercise_paths() -> list[Path]:
    paths = sorted((CONTENT / "exercises").glob("[0-9][0-9][0-9][0-9].typ"))
    if not paths:
        raise CheckError("content/exercises contains no numbered Typst files")
    return paths


def registry_source(paths: list[Path] | None = None) -> str:
    paths = paths or exercise_paths()
    aliases = [f"ex{path.stem}" for path in paths]
    imports = "\n".join(
        f'#import "exercises/{path.name}": item as {alias}'
        for path, alias in zip(paths, aliases)
    )
    members = ", ".join(aliases)
    return f'''// Generated by scripts/generate_registry.py. Do not edit by hand.
// Add or remove a numbered content/exercises/*.typ file, then run `just registry`.
{imports}

#let exercises = ({members},)

#let exercise-at(serial) = {{
  let matches = exercises.filter(item => item.serial == serial)
  assert(matches.len() == 1, message: "unknown or duplicate exercise serial " + str(serial))
  matches.first()
}}
'''


def write_registry() -> None:
    source = registry_source()
    if REGISTRY.is_file() and REGISTRY.read_text(encoding="utf-8") == source:
        return
    REGISTRY.write_text(source, encoding="utf-8")


def check_registry() -> None:
    expected = registry_source()
    actual = REGISTRY.read_text(encoding="utf-8") if REGISTRY.is_file() else ""
    if actual != expected:
        raise CheckError(
            f"{rel(REGISTRY)} is stale; run `python3 scripts/generate_registry.py`"
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    if parse_args().check:
        check_registry()
        print(f"exercise registry: ok ({len(exercise_paths())} files)")
    else:
        write_registry()
        print(f"Generated {rel(REGISTRY)} from {len(exercise_paths())} files")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except CheckError as exc:
        fail(str(exc))
